import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";
import Navbar2 from "@/components/Navbar2";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Patreon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script src="https://cdn.lordicon.com/lordicon.js"></script>
      </head>
      <body className={`${inter.className} min-h-screen w-full bg-neutral-950`}>
        <SessionWrapper>
        <Navbar />
        {/* <Navbar2/> */}
        <div className="relative min-h-[85.5vh] w-full">
          <div className="absolute inset-0 z-[-2] bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]"></div>
          {children}
        </div>
        <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
